logging:
  level: INFO
  loggers:
    currency-conversion-dropwizard-demo: DEBUG
# use the simple server factory if you only want to run on a single port
server:
  applicationConnectors:
    - type: http
      port: 8082
  adminConnectors:
    - type: http
      port: 8081


